"""add active conversation

Revision ID: d2a02486c60d
Revises: a4e1e8cf7b89
Create Date: 2026-06-11 11:53:42.952729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a02486c60d'
down_revision: Union[str, Sequence[str], None] = 'a4e1e8cf7b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_conversation_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'conversations', ['active_conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_conversation_id')
    # ### end Alembic commands ###
